"""Validated runtime representation of symmetry constraint orbits.

The symmetry transform builds compact tensor features because the inference
pipeline transports tensors between transforms and the sampler.  Downstream
code must not interpret those arrays independently: this module resolves them
once into a first-class layout with explicit groups, orbits, atom
correspondence, group actions, mobility modes, and bounds.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal

import torch


_ORBIT_FEATURES = {
    "motif_constraint_group_atom_indices",
    "motif_constraint_group_atom_mask",
    "motif_constraint_group_orbit_index",
    "motif_constraint_group_orbit_transform_id",
    "motif_constraint_orbit_master_group_index",
    "motif_constraint_orbit_mobility_mode",
    "motif_constraint_orbit_bounds",
}

_MOBILITY_SUBSPACES = {
    0: None,
    1: "radial",
    2: "radial_axial",
    3: "tilt_only",
    4: "bounded_se3",
}
_MOBILITY_PROPOSALS = {
    0: None,
    1: "denoiser_fit",
    2: "scaffold_objectives",
    3: "hoyeung_drag_compat",
}


@dataclass(frozen=True)
class ConstraintGroup:
    """One complete constrained motif instance in an orbit."""

    index: int
    orbit_index: int
    transform_id: int
    atom_indices: torch.Tensor


@dataclass(frozen=True)
class ConstraintOrbit:
    """One master constraint and all instances generated by group actions."""

    index: int
    constraint_orbit_id: str
    coupling_group_id: str
    master_group_index: int
    group_indices: tuple[int, ...]
    transform_ids: tuple[int, ...]
    mobility_mode: Literal["fixed", "orbit_rigid"]
    maximum_translation: float
    maximum_rotation_degrees: float
    mobility_subspace: str | None = None
    proposal_source: str | None = None
    schedule: tuple[float, float, float, float, float] | None = None
    objective_ids: tuple[str, ...] = ()

    @property
    def is_mobile(self) -> bool:
        return self.mobility_mode == "orbit_rigid"


@dataclass(frozen=True)
class ConstraintOrbitLayout:
    """Canonical interpretation of all runtime constraint-orbit features."""

    atom_count: int
    groups: tuple[ConstraintGroup, ...]
    orbits: tuple[ConstraintOrbit, ...]
    membership: torch.Tensor | None

    @property
    def mobile_orbits(self) -> tuple[ConstraintOrbit, ...]:
        return tuple(orbit for orbit in self.orbits if orbit.is_mobile)

    @classmethod
    def from_features(
        cls,
        features: dict[str, Any],
        *,
        atom_count: int,
        device: torch.device | str | None = None,
    ) -> "ConstraintOrbitLayout | None":
        """Resolve tensor transport features and fail closed on ambiguity.

        Returns ``None`` only when no orbit feature is present.  A partial
        feature set is an error rather than a request for legacy behavior.
        """

        present = _ORBIT_FEATURES & set(features)
        if not present:
            return None
        missing = _ORBIT_FEATURES - set(features)
        if missing:
            raise ValueError(
                "Constraint orbit features are incomplete: "
                f"missing {sorted(missing)}"
            )
        if atom_count <= 0:
            raise ValueError("Constraint orbit atom_count must be positive")

        group_atom_indices = torch.as_tensor(
            features["motif_constraint_group_atom_indices"],
            dtype=torch.long,
            device=device,
        )
        group_atom_mask = torch.as_tensor(
            features["motif_constraint_group_atom_mask"],
            dtype=torch.bool,
            device=device,
        )
        group_orbit_index = torch.as_tensor(
            features["motif_constraint_group_orbit_index"],
            dtype=torch.long,
            device=device,
        )
        group_transform_id = torch.as_tensor(
            features["motif_constraint_group_orbit_transform_id"],
            dtype=torch.long,
            device=device,
        )
        master_group_index = torch.as_tensor(
            features["motif_constraint_orbit_master_group_index"],
            dtype=torch.long,
            device=device,
        )
        mobility_mode = torch.as_tensor(
            features["motif_constraint_orbit_mobility_mode"],
            dtype=torch.long,
            device=device,
        )
        bounds = torch.as_tensor(
            features["motif_constraint_orbit_bounds"],
            dtype=torch.float32,
            device=device,
        )
        subspace_codes = torch.as_tensor(
            features.get(
                "motif_constraint_orbit_subspace",
                torch.where(mobility_mode == 1, 4, 0),
            ),
            dtype=torch.long,
            device=device,
        )
        proposal_codes = torch.as_tensor(
            features.get(
                "motif_constraint_orbit_proposal",
                torch.where(mobility_mode == 1, 1, 0),
            ),
            dtype=torch.long,
            device=device,
        )

        if group_atom_indices.ndim != 2:
            raise ValueError(
                "motif_constraint_group_atom_indices must have shape [G, M]"
            )
        if group_atom_mask.shape != group_atom_indices.shape:
            raise ValueError(
                "motif_constraint_group_atom_mask must match group atom indices"
            )
        group_count = group_atom_indices.shape[0]
        if group_count == 0:
            raise ValueError("Constraint orbit layout has no groups")
        if group_orbit_index.shape != (group_count,):
            raise ValueError(
                "motif_constraint_group_orbit_index must have shape [G]"
            )
        if group_transform_id.shape != (group_count,):
            raise ValueError(
                "motif_constraint_group_orbit_transform_id must have shape [G]"
            )

        orbit_count = master_group_index.numel()
        if master_group_index.ndim != 1 or orbit_count == 0:
            raise ValueError(
                "motif_constraint_orbit_master_group_index must have shape [O]"
            )
        if mobility_mode.shape != (orbit_count,):
            raise ValueError(
                "motif_constraint_orbit_mobility_mode must have shape [O]"
            )
        if bounds.shape != (orbit_count, 2):
            raise ValueError(
                "motif_constraint_orbit_bounds must have shape [O, 2]"
            )
        if subspace_codes.shape != (orbit_count,):
            raise ValueError(
                "motif_constraint_orbit_subspace must have shape [O]"
            )
        if proposal_codes.shape != (orbit_count,):
            raise ValueError(
                "motif_constraint_orbit_proposal must have shape [O]"
            )
        if any(
            int(value) not in _MOBILITY_SUBSPACES
            for value in subspace_codes.detach().cpu().tolist()
        ):
            raise ValueError("Unknown constraint-orbit mobility subspace")
        if any(
            int(value) not in _MOBILITY_PROPOSALS
            for value in proposal_codes.detach().cpu().tolist()
        ):
            raise ValueError("Unknown constraint-orbit proposal source")
        if torch.any((mobility_mode != 0) & (mobility_mode != 1)):
            raise ValueError(
                "Constraint orbit mobility mode may contain only 0 or 1"
            )
        if not torch.isfinite(bounds).all() or torch.any(bounds < 0.0):
            raise ValueError(
                "Constraint orbit mobility bounds must be finite and non-negative"
            )
        if torch.any(
            (group_orbit_index < 0) | (group_orbit_index >= orbit_count)
        ):
            raise ValueError("Every constraint group must reference a valid orbit")
        if torch.any(
            (master_group_index < 0) | (master_group_index >= group_count)
        ):
            raise ValueError("Every constraint orbit must reference a valid master")

        transform_keys = {
            int(transform_id)
            for transform_id in features.get("sym_transform", {})
        }
        if not transform_keys:
            raise ValueError(
                "Constraint orbits require runtime sym_transform entries"
            )

        membership_value = features.get(
            "motif_constraint_group_membership"
        )
        membership = None
        if membership_value is not None:
            membership = torch.as_tensor(
                membership_value,
                dtype=torch.bool,
                device=device,
            )
            if membership.shape != (group_count, atom_count):
                raise ValueError(
                    "motif_constraint_group_membership must have shape [G, L]"
                )

        groups: list[ConstraintGroup] = []
        atoms_by_group: list[set[int]] = []
        for group_index in range(group_count):
            valid = group_atom_mask[group_index]
            atom_indices = group_atom_indices[group_index, valid]
            if atom_indices.numel() == 0:
                raise ValueError(
                    f"Constraint group {group_index} has no atoms"
                )
            if torch.any((atom_indices < 0) | (atom_indices >= atom_count)):
                raise ValueError(
                    f"Constraint group {group_index} has invalid atoms"
                )
            if torch.unique(atom_indices).numel() != atom_indices.numel():
                raise ValueError(
                    f"Constraint group {group_index} repeats atoms"
                )
            masked_padding = group_atom_indices[group_index, ~valid]
            if masked_padding.numel() and torch.any(masked_padding != -1):
                raise ValueError(
                    "Masked constraint group atom slots must contain -1 padding"
                )
            atom_set = set(atom_indices.detach().cpu().tolist())
            if membership is not None:
                membership_set = set(
                    torch.nonzero(
                        membership[group_index],
                        as_tuple=False,
                    )
                    .flatten()
                    .detach()
                    .cpu()
                    .tolist()
                )
                if atom_set != membership_set:
                    raise ValueError(
                        "Constraint group compact atom slots disagree with "
                        f"membership for group {group_index}"
                    )
            transform_id = int(group_transform_id[group_index].item())
            if transform_id not in transform_keys:
                raise ValueError(
                    f"Constraint group {group_index} references unknown "
                    f"symmetry transform {transform_id}"
                )
            orbit_index = int(group_orbit_index[group_index].item())
            groups.append(
                ConstraintGroup(
                    index=group_index,
                    orbit_index=orbit_index,
                    transform_id=transform_id,
                    atom_indices=atom_indices,
                )
            )
            atoms_by_group.append(atom_set)

        orbits: list[ConstraintOrbit] = []
        atoms_by_orbit: list[set[int]] = []
        schedule_value = features.get("motif_constraint_orbit_schedule")
        schedule = (
            torch.as_tensor(
                schedule_value,
                dtype=torch.float32,
                device=device,
            )
            if schedule_value is not None
            else None
        )
        if schedule is not None and schedule.shape != (orbit_count, 5):
            raise ValueError(
                "motif_constraint_orbit_schedule must have shape [O, 5]"
            )
        objective_values = features.get(
            "motif_constraint_orbit_objective_ids",
            tuple(() for _ in range(orbit_count)),
        )
        if len(objective_values) != orbit_count:
            raise ValueError(
                "motif_constraint_orbit_objective_ids must have length O"
            )
        orbit_ids = tuple(
            str(value)
            for value in features.get(
                "motif_constraint_orbit_ids",
                tuple(f"orbit_{index}" for index in range(orbit_count)),
            )
        )
        component_ids = tuple(
            str(value)
            for value in features.get(
                "motif_constraint_orbit_component_ids",
                orbit_ids,
            )
        )
        if len(orbit_ids) != orbit_count or len(component_ids) != orbit_count:
            raise ValueError(
                "Constraint-orbit identifier features must have length O"
            )
        if (
            any(not value for value in orbit_ids + component_ids)
            or len(set(orbit_ids)) != orbit_count
            or len(set(component_ids)) != orbit_count
        ):
            raise ValueError(
                "Constraint-orbit and component identifiers must be non-empty "
                "and unique"
            )
        for orbit_index in range(orbit_count):
            orbit_group_indices = tuple(
                torch.nonzero(
                    group_orbit_index == orbit_index,
                    as_tuple=False,
                )
                .flatten()
                .detach()
                .cpu()
                .tolist()
            )
            if not orbit_group_indices:
                raise ValueError(
                    f"Constraint orbit {orbit_index} has no groups"
                )
            master = int(master_group_index[orbit_index].item())
            if master not in orbit_group_indices:
                raise ValueError(
                    f"Master group {master} is not in constraint orbit {orbit_index}"
                )
            atom_sizes = {
                len(atoms_by_group[index]) for index in orbit_group_indices
            }
            if len(atom_sizes) != 1:
                raise ValueError(
                    "All groups in one constraint orbit must have equal atom counts"
                )
            mode_value = int(mobility_mode[orbit_index].item())
            maximum_translation = float(bounds[orbit_index, 0].item())
            maximum_rotation = float(bounds[orbit_index, 1].item())
            mode: Literal["fixed", "orbit_rigid"] = (
                "orbit_rigid" if mode_value == 1 else "fixed"
            )
            subspace = _MOBILITY_SUBSPACES[
                int(subspace_codes[orbit_index].item())
            ]
            proposal_source = _MOBILITY_PROPOSALS[
                int(proposal_codes[orbit_index].item())
            ]
            if mode == "fixed" and (
                subspace is not None or proposal_source is not None
            ):
                raise ValueError(
                    "A fixed constraint orbit cannot declare mobility controls"
                )
            if mode == "orbit_rigid" and (
                subspace is None or proposal_source is None
            ):
                raise ValueError(
                    "A mobile constraint orbit requires subspace and proposal"
                )
            if mode == "orbit_rigid":
                if (
                    subspace in {"radial", "radial_axial"}
                    and maximum_translation <= 0.0
                ):
                    raise ValueError(
                        f"{subspace} mobility requires a positive "
                        "translation bound"
                    )
                if (
                    subspace == "tilt_only"
                    and maximum_rotation <= 0.0
                ):
                    raise ValueError(
                        "tilt_only mobility requires a positive rotation "
                        "bound"
                    )
                if subspace == "bounded_se3" and (
                    maximum_translation <= 0.0
                    or maximum_rotation <= 0.0
                ):
                    raise ValueError(
                        "bounded_se3 mobility requires positive translation "
                        "and rotation bounds"
                    )
            orbit_schedule = None
            if mode == "orbit_rigid":
                if schedule is not None:
                    schedule_row = schedule[orbit_index]
                    if torch.all(schedule_row == -1.0):
                        schedule_row = None
                    elif torch.any(schedule_row < 0.0):
                        raise ValueError(
                            "Constraint-orbit mobility schedule sentinel is "
                            "malformed"
                        )
                    if schedule_row is not None:
                        orbit_schedule = tuple(
                            float(value)
                            for value in schedule_row.tolist()
                        )
                if orbit_schedule is not None:
                    start, end, response, step_translation, step_rotation = (
                        orbit_schedule
                    )
                    if not (
                        0.0 <= start < end <= 1.0
                        and 0.0 < response <= 1.0
                        and step_translation > 0.0
                        and 0.0 < step_rotation <= 180.0
                    ):
                        raise ValueError(
                            "Constraint-orbit mobility schedule is invalid"
                        )
            transform_ids = tuple(
                groups[index].transform_id for index in orbit_group_indices
            )
            if len(set(transform_ids)) != len(transform_ids):
                raise ValueError(
                    f"Constraint orbit {orbit_index} repeats a group action"
                )
            orbits.append(
                ConstraintOrbit(
                    index=orbit_index,
                    constraint_orbit_id=orbit_ids[orbit_index],
                    coupling_group_id=component_ids[orbit_index],
                    master_group_index=master,
                    group_indices=orbit_group_indices,
                    transform_ids=transform_ids,
                    mobility_mode=mode,
                    maximum_translation=maximum_translation,
                    maximum_rotation_degrees=maximum_rotation,
                    mobility_subspace=subspace,
                    proposal_source=proposal_source,
                    schedule=orbit_schedule,
                    objective_ids=tuple(
                        str(value)
                        for value in objective_values[orbit_index]
                    ),
                )
            )
            atoms_by_orbit.append(
                set().union(
                    *(atoms_by_group[index] for index in orbit_group_indices)
                )
            )

        for orbit in orbits:
            if not orbit.is_mobile:
                continue
            for other in orbits:
                if (
                    other.index != orbit.index
                    and atoms_by_orbit[orbit.index]
                    & atoms_by_orbit[other.index]
                ):
                    raise ValueError(
                        "A mobile constraint orbit cannot overlap another orbit"
                    )

        return cls(
            atom_count=atom_count,
            groups=tuple(groups),
            orbits=tuple(orbits),
            membership=membership,
        )


# Compatibility names for the first interface-seed implementation.  New
# runtime code should use the topology-neutral names above; external callers
# can migrate without a flag day.
InterfaceConstraintGroup = ConstraintGroup
InterfaceConstraintOrbit = ConstraintOrbit
InterfaceConstraintOrbitLayout = ConstraintOrbitLayout


__all__ = [
    "ConstraintGroup",
    "ConstraintOrbit",
    "ConstraintOrbitLayout",
    "InterfaceConstraintGroup",
    "InterfaceConstraintOrbit",
    "InterfaceConstraintOrbitLayout",
]
