schema_version: 1
name: lrz-h100

slurm:
  partition: lrz-hgx-h100-94x4
  gres: gpu:1
  cpus: 12
  memory: 440G
  walltime: "08:00:00"

setup_commands:
  - source ~/software_paths.sh
  - source "$SHARED_MAMBAFORGE/etc/profile.d/conda.sh"
  - conda activate "$RC_FOUNDRY_ENV"

checkpoint: ~/.foundry/checkpoints/rfd3_latest.ckpt
foundry_checkpoint_dirs: ~/.foundry/checkpoints
