schema_version: 1
name: lrz-p100

slurm:
  partition: lrz-dgx-1-p100x8,lrz-hpe-p100x4
  gres: gpu:1
  cpus: 8
  memory: 120G
  walltime: "04:00:00"

setup_commands:
  - source ~/software_paths.sh
  - source "$SHARED_MAMBAFORGE/etc/profile.d/conda.sh"
  - conda activate "$RC_FOUNDRY_ENV"

checkpoint: ~/.foundry/checkpoints/rfd3_latest.ckpt
foundry_checkpoint_dirs: ~/.foundry/checkpoints
