name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install sphinx myst_parser furo sphinx-copybutton
      - name: Sphinx build
        run: |
          sphinx-build -M html docs/source/ docs/build/
      - name: Disable Jekyll
        run: touch docs/build/html/.nojekyll
      - name: Upload documentation site
        uses: actions/upload-artifact@v4
        with:
          name: documentation-site
          path: docs/build/html
          if-no-files-found: error

  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/production' }}
    needs: docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download documentation site
        uses: actions/download-artifact@v4
        with:
          name: documentation-site
          path: docs/build/html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true
